### ISSUE TITLE
Worklog of Sprint 1

### ISSUE THREAD

**Issue by sopheasuon** [pnc-virtual-company/2021-G5-VC2-PART2#15]

**Comment by sopheasuon** [comment]
My worklog of sprint 1.
[Sophea_Worklog_Template.xlsx](https://github.com/pnc-virtual-company/2021-G5-VC2-PART2/files/7759412/Sophea_Worklog_Template.xlsx)

**Comment by thinchrang** [comment]
[thin-Worklog Template.xlsx](https://github.com/pnc-virtual-company/2021-G5-VC2-PART2/files/7760965/thin-Worklog.Template.xlsx) 
Here is my worklog for the sprint 1. @Sreypichly

**Comment by Khimsreyhon** [comment]
Here is my worklog of sprint 1. @Sreypichly
[Sreyhon_khim Worklog Template.xlsx](https://github.com/pnc-virtual-company/2021-G5-VC2-PART2/files/7761223/Sreyhon_khim.Worklog.Template.xlsx)

**Comment by Lyhor-Ngorn** [comment]
[Worklog Template.xlsx](https://github.com/pnc-virtual-company/2021-G5-VC2-PART2/files/7761247/Worklog.Template.xlsx)
Good afternoon T. @Sreypichly.  Here is my worklog for sprint 1 and all the task for week 1.

**Comment by saravey2021** [comment]
Good afternoon T @Sreypichly. Here is my worklog for sprint 1 and all the task for week1.
[Worklog Template (Sara-Vey).xlsx](https://github.com/pnc-virtual-company/2021-G5-VC2-PART2/files/7761290/Worklog.Template.Sara-Vey.xlsx)

**Comment by chum-ch** [comment]
Teacher:@Sreypichly
Here is my worklog for sprint 1 and all the tasks for the week1
[Worklog Chum-yoeurn.xlsx](https://github.com/pnc-virtual-company/2021-G5-VC2-PART2/files/7762493/Worklog.Chum-yoeurn.xlsx)
