### ISSUE TITLE
Design ERD

### ISSUE THREAD

**Issue by sopheasuon** [pnc-virtual-company/2021-G5-VC2-PART2#2]
=> update relation
=> design entity and attributes

**Comment by Lyhor-Ngorn** [comment]
![Screenshot 2021-12-17 080612](https://user-images.githubusercontent.com/73428895/146489564-33623501-cbd8-4430-8004-7cd0fb5dde8c.png)

have only one table to control user
@Sovanda-chib

**Comment by sopheasuon** [comment]
Done
