### ISSUE TITLE
[sign-in]Update component sign in diagram

### ISSUE THREAD

**Issue by sopheasuon** [pnc-virtual-company/2021-G5-VC2-PART2#3]

**Comment by Lyhor-Ngorn** [comment]
[CD Diagram.pptx](https://github.com/pnc-virtual-company/2021-G5-VC2-PART2/files/7731308/CD.Diagram.pptx)
this is our component diagram about sign in and sign up. please glad to check it. @Sovanda-chib

**Comment by Lyhor-Ngorn** [comment]
![image](https://user-images.githubusercontent.com/73428895/146739652-7ed88db7-1f3d-4283-a863-2e976ba47a73.png)
This is the sign in diagram

**Comment by sopheasuon** [comment]
Done
